# yaml-language-server: $schema=https://raw.githubusercontent.com/mbrt/gencmd/refs/heads/main/config-schema.json

# The provider is auto-detected from environment variables, unless overridden below
# llm:
#   provider: googleai
#   modelName: gemini-2.5-flash-lite
#   promptTemplate: |
#     You are a command line expert. Generate up to 5 shell command alternatives that implement the following description:
#     {{.UserInput}}
#
#   openai:  # optional OpenAI configuration
#     baseUrl: https://api.openai.com/v1
